version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hotoru
      MONGO_INITDB_ROOT_PASSWORD: gYNDxLjaTWbEX85
      MONGO_INITDB_DATABASE: hotoru

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hotoru
      ME_CONFIG_MONGODB_ADMINPASSWORD: gYNDxLjaTWbEX85